# Código para capturar tabelas de classificação ano a ano e transformar em CSV

In [26]:
# Trazer bibliotecas
import pandas as pd
from bs4 import BeautifulSoup

In [27]:
# Arquivo salvo como html
with open(r"HTML_Classificacao\25-26\NBB_25_avg.html", "r", encoding="latin-1") as f:
    conteudo = f.read()

In [28]:
# Criação de parser
soup = BeautifulSoup(conteudo, "html.parser")

In [29]:
# Pega todas as linhas da tabela
linhas = soup.find_all('tr')

In [30]:
# Extrai o texto de cada célula
data = []
for linha in linhas:
    cols = linha.find_all(['td', 'th'])
    cols = [col.get_text(strip=True) for col in cols]
    data.append(cols)

In [31]:
# Exibe a tabela selecionada
df = pd.DataFrame(data[1:], columns=data[0])

In [32]:
df.head()

,#,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
0,#,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
1,1.,Franca,38,39.7,90.8,31.2,64.6,.483,10.1,29.0,...,23.5,.780,10.5,28.9,39.5,19.5,8.1,1.8,12.2,16.9
2,2.,Minas,38,40.1,88.0,30.7,66.2,.463,9.9,28.5,...,23.4,.717,12.2,29.1,41.3,20.8,7.4,3.1,13.8,19.7
3,3.,Flamengo,38,39.6,87.5,30.6,65.5,.468,11.6,31.7,...,20.1,.727,10.5,26.2,36.8,19.6,8.1,1.3,12.8,19.7
4,4.,Pinheiros Sky,38,39.7,85.3,30.1,66.9,.449,10.9,32.6,...,19.2,.739,13.1,28.5,41.6,19.3,7.5,2.4,13.2,20.2

In [33]:
# Conferencia de valores inicial
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   #       21 non-null     object
 1   Team    21 non-null     object
 2   GP      21 non-null     object
 3   MPG     21 non-null     object
 4   PPG     21 non-null     object
 5   FGM     21 non-null     object
 6   FGA     21 non-null     object
 7   FG%     21 non-null     object
 8   3PM     21 non-null     object
 9   3PA     21 non-null     object
 10  3P%     21 non-null     object
 11  FTM     21 non-null     object
 12  FTA     21 non-null     object
 13  FT%     21 non-null     object
 14  ORB     21 non-null     object
 15  DRB     21 non-null     object
 16  RPG     21 non-null     object
 17  APG     21 non-null     object
 18  SPG     21 non-null     object
 19  BPG     21 non-null     object
 20  TOV     21 non-null     object
 21  PF      21 non-null     object
dtypes: object(22)
memory usage: 3.7+ KB

In [34]:
# Apagar coluna index da tabela origem
df.drop(columns= '#', inplace=True)
df.drop(axis = 1, index= 0, inplace=True)

In [35]:
# Conferência de valores
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 1 to 20
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    20 non-null     object
 1   GP      20 non-null     object
 2   MPG     20 non-null     object
 3   PPG     20 non-null     object
 4   FGM     20 non-null     object
 5   FGA     20 non-null     object
 6   FG%     20 non-null     object
 7   3PM     20 non-null     object
 8   3PA     20 non-null     object
 9   3P%     20 non-null     object
 10  FTM     20 non-null     object
 11  FTA     20 non-null     object
 12  FT%     20 non-null     object
 13  ORB     20 non-null     object
 14  DRB     20 non-null     object
 15  RPG     20 non-null     object
 16  APG     20 non-null     object
 17  SPG     20 non-null     object
 18  BPG     20 non-null     object
 19  TOV     20 non-null     object
 20  PF      20 non-null     object
dtypes: object(21)
memory usage: 3.4+ KB

In [36]:
# Conversão de tipos de dados
df.drop(columns=['GP', 'MPG', 'PF'], inplace=True)
for col in df.columns:
    if col not in ['Team', 'GP']:
        df[col]=df[col].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 1 to 20
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    20 non-null     object
 1   PPG     20 non-null     float64
 2   FGM     20 non-null     float64
 3   FGA     20 non-null     float64
 4   FG%     20 non-null     float64
 5   3PM     20 non-null     float64
 6   3PA     20 non-null     float64
 7   3P%     20 non-null     float64
 8   FTM     20 non-null     float64
 9   FTA     20 non-null     float64
 10  FT%     20 non-null     float64
 11  ORB     20 non-null     float64
 12  DRB     20 non-null     float64
 13  RPG     20 non-null     float64
 14  APG     20 non-null     float64
 15  SPG     20 non-null     float64
 16  BPG     20 non-null     float64
 17  TOV     20 non-null     float64
dtypes: float64(17), object(1)
memory usage: 2.9+ KB

In [37]:
df.head()

,Team,PPG,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV
1,Franca,90.8,31.2,64.6,0.483,10.1,29.0,0.348,18.3,23.5,0.780,10.5,28.9,39.5,19.5,8.1,1.8,12.2
2,Minas,88.0,30.7,66.2,0.463,9.9,28.5,0.347,16.8,23.4,0.717,12.2,29.1,41.3,20.8,7.4,3.1,13.8
3,Flamengo,87.5,30.6,65.5,0.468,11.6,31.7,0.365,14.6,20.1,0.727,10.5,26.2,36.8,19.6,8.1,1.3,12.8
4,Pinheiros Sky,85.3,30.1,66.9,0.449,10.9,32.6,0.336,14.2,19.2,0.739,13.1,28.5,41.6,19.3,7.5,2.4,13.2
5,Corinthians,85.2,30.6,64.6,0.474,10.7,28.6,0.374,13.3,17.3,0.771,11.5,28.5,40.0,21.7,6.0,2.8,15.1

In [38]:
# Arquivo salvo como html
with open(r"HTML_Classificacao\25-26\NBB_25_advanced.html", "r", encoding="latin-1") as f:
    conteudo = f.read()

In [39]:
# Criação de parser
soup = BeautifulSoup(conteudo, "html.parser")

In [40]:
# Pega todas as linhas da tabela
linhas = soup.find_all('tr')

In [41]:
# Extrai o texto de cada célula
data = []
for linha in linhas:
    cols = linha.find_all(['td', 'th'])
    cols = [col.get_text(strip=True) for col in cols]
    data.append(cols)

In [42]:
# Exibe a tabela selecionada
df2 = pd.DataFrame(data[1:], columns=data[0])

In [43]:
# Segundo df a ser anexado
df2.head()

,#,Team,TS%,eFG%,Total S%,ORB%,DRB%,TRB%,AST%,TOV%,STL%,BLK%,PPS,FIC40,ORtg,DRtg,eDiff,Poss,Pace
0,1.,Franca,.606,.561,161.0,30.4,74.3,53.7,62.5,14.0,10.8,5.0,1.4,75.2,120.1,101.7,18.4,"2,872.4",75.5
1,2.,Pinheiros Sky,.565,.531,152.4,34.6,73.3,54.2,64.1,14.9,10.2,7.0,1.3,68.7,115.0,99.9,15.1,"2,817.5",74.2
2,3.,Uniceub-BRB-Brasilia,.551,.512,149.8,30.4,71.5,51.2,67.4,15.4,11.2,7.2,1.3,64.1,109.2,96.3,12.9,"2,839.5",73.8
3,4.,Flamengo,.588,.556,155.9,28.8,70.4,49.9,64.0,14.6,10.9,3.6,1.3,68.1,115.7,104.5,11.2,"2,871.9",75.5
4,5.,Minas,.575,.538,152.7,32.2,71.0,52.4,67.7,15.3,9.7,8.0,1.3,71.1,113.8,105.0,8.8,"2,937.9",76.8

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   #         20 non-null     object
 1   Team      20 non-null     object
 2   TS%       20 non-null     object
 3   eFG%      20 non-null     object
 4   Total S%  20 non-null     object
 5   ORB%      20 non-null     object
 6   DRB%      20 non-null     object
 7   TRB%      20 non-null     object
 8   AST%      20 non-null     object
 9   TOV%      20 non-null     object
 10  STL%      20 non-null     object
 11  BLK%      20 non-null     object
 12  PPS       20 non-null     object
 13  FIC40     20 non-null     object
 14  ORtg      20 non-null     object
 15  DRtg      20 non-null     object
 16  eDiff     20 non-null     object
 17  Poss      20 non-null     object
 18  Pace      20 non-null     object
dtypes: object(19)
memory usage: 3.1+ KB

In [45]:
df2.drop(columns=['#', 'Total S%', 'PPS', 'FIC40', 'Poss'], inplace=True)

In [46]:
# df2 = df2.drop(0)

In [47]:
df2.columns

Index(['Team', 'TS%', 'eFG%', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'TOV%', 'STL%',
       'BLK%', 'ORtg', 'DRtg', 'eDiff', 'Pace'],
      dtype='object')

In [48]:
cols = ['TS%', 'eFG%', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'TOV%', 'STL%',
       'BLK%', 'ORtg', 'DRtg', 'eDiff', 'Pace']
df2[cols] = df2[cols].astype(float)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    20 non-null     object
 1   TS%     20 non-null     float64
 2   eFG%    20 non-null     float64
 3   ORB%    20 non-null     float64
 4   DRB%    20 non-null     float64
 5   TRB%    20 non-null     float64
 6   AST%    20 non-null     float64
 7   TOV%    20 non-null     float64
 8   STL%    20 non-null     float64
 9   BLK%    20 non-null     float64
 10  ORtg    20 non-null     float64
 11  DRtg    20 non-null     float64
 12  eDiff   20 non-null     float64
 13  Pace    20 non-null     float64
dtypes: float64(13), object(1)
memory usage: 2.3+ KB

In [49]:
# Arquivo salvo como html
with open(r"HTML_Classificacao\25-26\NBB_25_misc.html", "r", encoding="latin-1") as f:
    conteudo = f.read()

In [50]:
# Criação de parser
soup = BeautifulSoup(conteudo, "html.parser")

In [51]:
# Pega todas as linhas da tabela
linhas = soup.find_all('tr')

In [52]:
# Extrai o texto de cada célula
data = []
for linha in linhas:
    cols = linha.find_all(['td', 'th'])
    cols = [col.get_text(strip=True) for col in cols]
    data.append(cols)

In [53]:
# Exibe a tabela selecionada
df3 = pd.DataFrame(data[1:], columns=data[0])

In [54]:
# Terceira tabela a ser anexada
df3.head()

,#,Team,Dbl Dbl,Tpl Dbl,40 Pts,20 Reb,20 Ast,5 Stl,5 Blk,High Game,MOV,Techs,HOB,Ast/TO,Stl/TO,FT/FGA,W's,L's,Win %
0,1.,Uniao Corinthians,28,1,1,0,0,1,0,103,-1.7,0,1.631,1.3,0.4,.210,19,19,.500
1,2.,Bauru,28,1,0,0,0,6,0,107,1.1,0,1.722,1.5,0.6,.214,21,17,.553
2,3.,Franca,25,4,0,0,0,4,0,116,13.9,0,1.625,1.6,0.7,.284,32,6,.842
3,4.,Uniceub-BRB-Brasilia,19,0,0,0,0,2,1,109,9.6,0,1.674,1.4,0.6,.229,28,10,.737
4,5.,Paulistano,17,1,0,0,0,1,0,109,5.1,0,1.515,1.2,0.6,.211,24,14,.632

In [55]:
for col in df3.columns:
    if col not in ["Team", "Ast/TO", "W's", "Win %"]:
        df3=df3.drop(columns=[col])

In [56]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    20 non-null     object
 1   Ast/TO  20 non-null     object
 2   W's     20 non-null     object
 3   Win %   20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

In [57]:
df3['Ast/TO'] = df3['Ast/TO'].astype(float)
df3['Win %'] = df3['Win %'].astype(float)
df3["W's"] = df3["W's"].astype(int)

In [58]:
# Anexar colunas de todas as tabelas criando um único Df
df_f1 = pd.merge(df, df2, on='Team', how='left')

In [59]:
df_final = pd.merge(df_f1, df3, on='Team', how='left')

In [60]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 34 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    20 non-null     object
 1   PPG     20 non-null     float64
 2   FGM     20 non-null     float64
 3   FGA     20 non-null     float64
 4   FG%     20 non-null     float64
 5   3PM     20 non-null     float64
 6   3PA     20 non-null     float64
 7   3P%     20 non-null     float64
 8   FTM     20 non-null     float64
 9   FTA     20 non-null     float64
 10  FT%     20 non-null     float64
 11  ORB     20 non-null     float64
 12  DRB     20 non-null     float64
 13  RPG     20 non-null     float64
 14  APG     20 non-null     float64
 15  SPG     20 non-null     float64
 16  BPG     20 non-null     float64
 17  TOV     20 non-null     float64
 18  TS%     20 non-null     float64
 19  eFG%    20 non-null     float64
 20  ORB%    20 non-null     float64
 21  DRB%    20 non-null     float64
 22  TRB%    20 non-null     float64
 23  AST%    20 non-null     float64
 24  TOV%    20 non-null     float64
 25  STL%    20 non-null     float64
 26  BLK%    20 non-null     float64
 27  ORtg    20 non-null     float64
 28  DRtg    20 non-null     float64
 29  eDiff   20 non-null     float64
 30  Pace    20 non-null     float64
 31  Ast/TO  20 non-null     float64
 32  W's     20 non-null     int64
 33  Win %   20 non-null     float64
dtypes: float64(32), int64(1), object(1)
memory usage: 5.4+ KB

In [61]:
df_final.to_csv('Classificacao_NBB/NBB_25_teams.csv', index=False)