# Tratamento das tabelas de jogos da NBB
* Importação das tabelas em formato excel de 9 temporadas diferentes
* Tratamento de células e colunas para valores que podem ser usados pelo modelo
* Upload dos arquivos que serão usados para o cálculo do elo das equipes, previsão de resultados e de calendário futuro

In [86]:
import pandas as pd
import openpyxl
from pathlib import Path

In [87]:
'''
Definição dos caminhos do sistema para importar e exportar arquivos
Definição de um dataframe para cada tabela excel
'''

BASE_DIR = Path.cwd().parent
OUT_DIR = Path.cwd().parent / "historico_nbb" / "data"

df_26 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_26.xlsx")
df_25 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_25.xlsx")
df_24 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_24.xlsx")
df_23 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_23.xlsx")
df_22 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_22.xlsx")
df_21 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_21.xlsx")
df_20 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_20.xlsx")
df_18 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_18.xlsx")
df_17 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_17.xlsx")
df_16 = pd.read_excel(BASE_DIR / "historico_nbb" / "historico_seasons" / "Tabela_de_jogos_16.xlsx")

In [88]:
# Verificação do formato da tabela
df_21.head()

,NBB 2021/2022\nTABELA DE JOGOS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,#,DATA,CASA,NaN,PLACAR,VISITANTE,NaN,RODADA,FASE,GINÁSIO,NaN,NaN
1,1,23/10/2021 16:10,JOGO 1 - 23/10/2021 16:10,São Paulo,NaN,61 X\n86,Flamengo,NaN,1ª,1º,Ginásio Pol. Dr. Antônio L. Nunes Galvão - (Mo...,HOSPEDE-SE AQUI
2,2,25/10/2021 20:30,JOGO 2 - 25/10/2021 20:30,Luvix/União Corinthians,NaN,59 X\n77,Minas,NaN,2ª,1º,Gin. Poliesportivo Arnão\nHOSPEDE-SE AQUI,HOSPEDE-\nSE AQUI
3,3,26/10/2021 19:00,JOGO 3 - 26/10/2021 19:00,Bauru,NaN,76 X\n87,Sesi Franca,NaN,2ª,1º,Gin. Panela de Pressão\nHOSPEDE-SE AQUI,HOSPEDE-\nSE AQUI
4,4,26/10/2021 20:00,JOGO 4 - 26/10/2021 20:00,São Paulo,NaN,76 X\n78,Cerrado Basquete,NaN,2ª,1º,Ginásio Pol. Dr. Antônio L. Nunes Galvão - (Mo...,HOSPEDE-SE AQUI

In [89]:
df_17['N44'] = 44
df_17.head()

,NBB 2017/2018\nTABELA DE JOGOS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,N44
0,#,DATA,CASA,NaN,PLACAR,VISITANTE,NaN,FASE,GINÁSIO,NaN,44
1,1,04/11/2017 14:00,JOGO 1 - 04/11/2017 14:00,Bauru,NaN,72 X 71,Paulistano,NaN,1º,Gin. Antonio Prado Jr,44
2,2,06/11/2017 20:10,JOGO 2 - 06/11/2017 20:10,Sesi Franca,NaN,73 X 77,Campo Mourão,NaN,1º,Ginásio Pedrocão,44
3,3,07/11/2017 19:30,JOGO 3 - 07/11/2017 19:30,Minas,NaN,82 X 81,Vasco da Gama,NaN,1º,Arena Minas,44
4,4,07/11/2017 20:00,JOGO 4 - 07/11/2017 20:00,L. Sorocabana,NaN,91 X 76,Basq. Cearense,NaN,1º,Ginásio Gualberto Moreira,44

In [90]:
df_21 = df_21.drop(columns='Unnamed: 11')

In [91]:
# Criação de uma função que seja capaz de fazer a limpeza para todos os dataframes
def limpeza_colunas(
        DF: pd.DataFrame,
        SEASON: int,
) -> pd.DataFrame:
    df = DF
    lista_cols = ['#', 'Season', 'Rodada', 'Casa', 'Placar_casa', 'Placar_visitante', 'Visitante', 'N1', 'Fase', 'N2', 'N3']
    df.columns = lista_cols
    mask = ['Season', 'Casa', 'Placar_casa', 'Placar_visitante', 'Visitante']
    df = df[mask]
    df = df[df['Placar_casa'] != "PLACAR"]
    df['Season'] = SEASON
    df[['Placar_casa', 'Placar_visitante']] = df['Placar_visitante'].str.extract(r'(\d+)\D+(\d+)')

    return df

df_26 = limpeza_colunas(df_26, 2026)
df_25 = limpeza_colunas(df_25, 2025)
df_24 = limpeza_colunas(df_24, 2024)
df_23 = limpeza_colunas(df_23, 2023)
df_22 = limpeza_colunas(df_22, 2022)
df_21 = limpeza_colunas(df_21, 2021)
df_20 = limpeza_colunas(df_20, 2020)
df_18 = limpeza_colunas(df_18, 2018)
df_17 = limpeza_colunas(df_17, 2017)
df_16 = limpeza_colunas(df_16, 2016)

In [92]:
# Verificação de sucesso
df_20.head()

   Season             Casa Placar_casa Placar_visitante        Visitante
1    2020      VipTech CMB          61               74  Fortaleza B. C.
2    2020         Flamengo         102               68            Minas
3    2020        UNIFACISA          86               88      VipTech CMB
4    2020      Corinthians         109               86      Sesi Franca
5    2020  Fortaleza B. C.          69               82         Flamengo

In [93]:
# verificação de nulos
df_26.info()

<class 'pandas.DataFrame'>
Index: 153 entries, 1 to 158
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            153 non-null    int64
 1   Casa              153 non-null    str
 2   Placar_casa       0 non-null      str
 3   Placar_visitante  0 non-null      str
 4   Visitante         153 non-null    str
dtypes: int64(1), str(4)
memory usage: 7.2 KB

In [94]:
'''
Como a tabela da temporada 26/27 será usada para realizar as previsões de calendário e confronto
não é necessário manter as colunas de placar
'''
df_26 = df_26.drop(columns=['Placar_casa', 'Placar_visitante'])
df_26.head()

   Season                    Casa            Visitante
1    2026           Mogi Basquete          Corinthians
2    2026  Caxias do Sul Basquete             Cruzeiro
3    2026               UNIFACISA        Basket Osasco
4    2026                Flamengo         Bauru Basket
5    2026             Sesi Franca  São José Basketball

In [95]:
'''
Juntando as tabelas de resultados históricos em uma única tabela
que será utilizada para limpeza dos nomes das equipes e cálculo de elo
'''

df_lista = [df_16, df_17, df_18, df_20, df_21, df_22, df_23, df_24, df_25]

df_historico = pd.concat(df_lista)
df_historico.info()

<class 'pandas.DataFrame'>
Index: 2784 entries, 1 to 460
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            2784 non-null   int64
 1   Casa              2784 non-null   str
 2   Placar_casa       2784 non-null   str
 3   Placar_visitante  2784 non-null   str
 4   Visitante         2784 non-null   str
dtypes: int64(1), str(4)
memory usage: 130.5 KB

In [96]:
df_historico['Casa'].value_counts()

Casa
Flamengo                           175
Pinheiros                          172
Sesi Franca                        169
Paulistano                         160
Corinthians                        132
Mogi                               120
UNIFACISA                          114
Pato Basquete                      106
São Paulo                          100
Bauru                               96
Caxias do Sul Basquete              92
Botafogo                            90
Minas                               89
Bauru Basket                        85
Vasco da Gama                       64
BRB/Brasília                        62
Fortaleza B. C.                     55
Basq. Cearense                      49
KTO Minas                           48
CAIXA/Brasília Basquete             45
R10 Score Vasco da Gama             41
Ceisc/União Corinthians             40
Vitória                             37
Cerrado Basquete                    35
União Corinthians                   35
123 Minas                           34
Brasília                            33
Rio Claro                           33
Caxias do Sul                       32
Fortaleza B. C. / CFO               31
Cerrado                             30
L. Sorocabana                       28
Joinville / AABJ                    27
Mogi Basquete                       23
Cruzeiro                            21
Conta Simples Rio Claro             21
Paulistano/CORPe                    20
Mr. Moo São José Basketball         20
Coop/São José Basketball            19
Farma Conde/São José Basketball     19
Basket Osasco                       19
Fortaleza Basquete Cearense         19
Franca                              17
Campo Mourão                        17
Oscar São José Basketball           17
KTO/Caxias do Sul                   16
Luvix/União Corinthians             16
Macaé Basquete                      15
VipTech CMB                         15
São José                            14
Campo\nMourão                       13
Desk Manager Mogi Basquete           4
Name: count, dtype: int64

In [97]:
map = {                        
    'Paulistano/CORPe':'Paulistano',                                                
    'Mogi Basquete' :'Mogi',                                                         
    'Bauru Basket':'Bauru',                               
    'Caxias do Sul':'Caxias do Sul Basquete',                                          
    'KTO Minas':'Minas',                                                       
    'R10 Score Vasco da Gama':'Vasco da Gama',                       
    'BRB/Brasília':'Brasília',                        
    'Fortaleza B. C.': 'Basquete Cearense',
    'Basq. Cearense': 'Basquete Cearense',
    'CAIXA/Brasília Basquete': 'Brasília',
    'Ceisc/União Corinthians': 'União Corinthians',
    'Cerrado': 'Cerrado Basquete',
    '123 Minas': 'Minas',
    'Fortaleza B. C. / CFO': 'Basquete Cearense',
    'Conta Simples Rio Claro': 'Rio Claro',
    'Mr. Moo São José Basketball': 'São José',
    'Coop/São José Basketball': 'São José',
    'Farma Conde/São José Basketball': 'São José',
    'Fortaleza Basquete Cearense': 'Basquete Cearense',
    'Oscar São José Basketball': 'São José',
    'KTO/Caxias do Sul': 'Caxias do Sul Basquete',
    'Luvix/União Corinthians': 'União Corinthians',
    'Campo\nMourão': 'Campo Mourão',
    'Desk Manager Mogi Basquete': 'Mogi',
    'Sesi Franca':'Franca',
    'São José Basketball': 'São José'
}

df_historico['Casa'] = df_historico['Casa'].replace(map)
df_historico['Visitante'] = df_historico['Visitante'].replace(map)

In [98]:
'''
Verificando possíveis correções de valores a serem feitos na coluna Visitante
'''

df_historico['Visitante'].value_counts()

Visitante
Franca                    179
Flamengo                  178
Bauru                     177
Paulistano                174
Pinheiros                 173
Minas                     171
Basquete Cearense         154
Mogi                      146
Brasília                  141
Caxias do Sul Basquete    139
Corinthians               132
UNIFACISA                 115
Pato Basquete             109
Vasco da Gama             106
São Paulo                 102
Botafogo                   91
São José                   91
União Corinthians          91
Cerrado Basquete           65
Rio Claro                  54
Vitória                    37
Campo Mourão               31
L. Sorocabana              28
Joinville / AABJ           27
Cruzeiro                   21
Basket Osasco              19
Macaé Basquete             15
VipTech CMB                15
Macaé\nBasquete             1
Basq.\nCearense             1
Vasco da\nGama              1
Name: count, dtype: int64

In [99]:
# Correções finais de nomes de equipes
map2 ={
    'Macaé\nBasquete': 'Macaé Basquete',
    'Basq.\nCearense': 'Basquete Cearense',            
    'Vasco da\nGama': 'Vasco da Gama'
}

df_historico['Visitante'] = df_historico['Visitante'].replace(map2)

In [100]:
df_historico['Visitante'].value_counts()

Visitante
Franca                    179
Flamengo                  178
Bauru                     177
Paulistano                174
Pinheiros                 173
Minas                     171
Basquete Cearense         155
Mogi                      146
Brasília                  141
Caxias do Sul Basquete    139
Corinthians               132
UNIFACISA                 115
Pato Basquete             109
Vasco da Gama             107
São Paulo                 102
Botafogo                   91
São José                   91
União Corinthians          91
Cerrado Basquete           65
Rio Claro                  54
Vitória                    37
Campo Mourão               31
L. Sorocabana              28
Joinville / AABJ           27
Cruzeiro                   21
Basket Osasco              19
Macaé Basquete             16
VipTech CMB                15
Name: count, dtype: int64

In [101]:
df_historico['Casa'].value_counts()

Casa
Franca                    186
Bauru                     181
Paulistano                180
Flamengo                  175
Pinheiros                 172
Minas                     171
Basquete Cearense         154
Mogi                      147
Brasília                  140
Caxias do Sul Basquete    140
Corinthians               132
UNIFACISA                 114
Pato Basquete             106
Vasco da Gama             105
São Paulo                 100
União Corinthians          91
Botafogo                   90
São José                   89
Cerrado Basquete           65
Rio Claro                  54
Vitória                    37
Campo Mourão               30
L. Sorocabana              28
Joinville / AABJ           27
Cruzeiro                   21
Basket Osasco              19
Macaé Basquete             15
VipTech CMB                15
Name: count, dtype: int64

In [102]:
df_historico.info()

<class 'pandas.DataFrame'>
Index: 2784 entries, 1 to 460
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            2784 non-null   int64
 1   Casa              2784 non-null   str
 2   Placar_casa       2784 non-null   str
 3   Placar_visitante  2784 non-null   str
 4   Visitante         2784 non-null   str
dtypes: int64(1), str(4)
memory usage: 130.5 KB

In [103]:
# Igualando os nomes das equipes nos dois dataframes
df_26['Casa'].value_counts()

Casa
Caxias do Sul Basquete     9
UNIFACISA                  9
Flamengo                   9
Sesi Franca                9
CAIXA/Brasília Basquete    9
Corinthians                9
Cruzeiro                   9
São José Basketball        9
Basket Osasco              9
Mogi Basquete              8
Ceisc/União Corinthians    8
Basquete Cearense          8
Bauru Basket               8
Pato Basquete              8
Minas                      8
Pinheiros                  8
Paulistano                 8
Botafogo                   8
Name: count, dtype: int64

In [104]:
df_26['Casa'] = df_26['Casa'].replace(map)
df_26['Visitante'] = df_26['Visitante'].replace(map)

In [105]:
df_26['Casa'].value_counts()

Casa
Caxias do Sul Basquete    9
UNIFACISA                 9
Flamengo                  9
Franca                    9
Brasília                  9
Corinthians               9
Cruzeiro                  9
São José                  9
Basket Osasco             9
Mogi                      8
União Corinthians         8
Basquete Cearense         8
Bauru                     8
Pato Basquete             8
Minas                     8
Pinheiros                 8
Paulistano                8
Botafogo                  8
Name: count, dtype: int64

In [106]:
df_26['Visitante'].value_counts()

Visitante
Bauru                     9
Pinheiros                 9
Minas                     9
Botafogo                  9
Mogi                      9
Paulistano                9
Pato Basquete             9
União Corinthians         9
Basquete Cearense         9
Corinthians               8
Cruzeiro                  8
Basket Osasco             8
São José                  8
Franca                    8
UNIFACISA                 8
Brasília                  8
Caxias do Sul Basquete    8
Flamengo                  8
Name: count, dtype: int64

In [108]:
# Salvando os dataframes resultantes

df_historico.to_csv(OUT_DIR / "historico_nbb.csv", index=False)
df_26.to_csv(OUT_DIR / "calendario_26_nbb.csv", index=False)